### ISSUE TITLE
Приложение выгружается из памяти на Android 6.0

### ISSUE THREAD

**Issue by Katarn** [kovinevmv/PhoneDetector#2]
Не помогает даже включенная защита от выгрузки, из настроек системы.

Используется оболочка EMUI 4.1.

**Comment by kovinevmv** [comment]
Смотрите 4pda как заставлять приложения не засыпать. Ничем не могу помочь, нет такого устройства, чтобы проверить

**Comment by Katarn** [comment]
Не, Штирлицу показалось. Сорян.
